version: '3.0'

services:
  web:
    image: alexcheng/magento
    ports:
      - "80:80"
    links:
      - db
    env_file:
      - env
  
  db:
    image: mysql:5.6.23
    env_file:
      - env
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db